version: "3.4"

services:
  disaster:
    ports:
      - 5170:80
    build:
      context: .
      args:
        - GoogleMapsAPIKey=$GoogleMapsAPIKey
        - GoogleMapsMapId=$GoogleMapsMapId
    volumes:
      - type: bind
        source: ./geojson
        target: /usr/share/nginx/html/geojson
